server:
  port: 8084
spring:
  application:
    name: shelf-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/secret_shelf?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:TuNuevaContraseña}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
